--drop table if exists "acc_core_recurring_invoices" cascade;
CREATE TABLE IF NOT EXISTS "acc_core_recurring_invoices" (
	"id" serial,
  	"uid" varchar(255) not null default '',
  	"udid" varchar(255) not null default '',
    "wid" varchar(255) not null default '',
	"company_id" integer not null default 0 ,
	"profile_name" varchar(255) not null default '' ,
	"contact_id"  integer not null default 0,
	"starts_at" timestamp,
	"ends_at" timestamp,
	"repeat_on" integer not null default 0,
	"currency_code"  integer not null default 0,
	"currency_rate" decimal not null default 0.00,
	"payment_term_id" integer not null default 0,
	"status" varchar(255) not null default '' ,
	"sub_total" decimal not null default 0.00,
	"tax_amount" decimal not null default 0.00,
	"discount" decimal not null default 0.00,
	"adjustment" decimal not null default 0.00,
	"shipping_charge" decimal not null default 0.00,
	"total" decimal not null default 0.00,
	"reference" varchar(255) not null default '' ,
	"notes" varchar(255) not null default '',
	"terms_conditions" text,
	is_active smallint DEFAULT 0 NOT NULL,
    is_synced smallint DEFAULT 0 NOT NULL,
    "created_at" timestamp,
	"updated_at" timestamp,
	"deleted_at" timestamp,
	PRIMARY KEY (id)
);

--drop table if exists "acc_core_recurring_invoice_items" cascade;
CREATE TABLE IF NOT EXISTS "acc_core_recurring_invoice_items" (
	"id" serial,
  	"uid" varchar(255) not null default '',
  	"udid" varchar(255) not null default '',
    "wid" varchar(255) not null default '',
	"company_id" integer not null default 0 ,
	"recurring_invoice_id" integer not null default 0,
	"item_id" integer not null default 0,
	"service_id" integer not null default 0,
	"name" varchar(255) not null default '' ,
	"sku" varchar(255) not null default '' ,
	"quantity" integer not null default 0,
	"price" decimal not null default 0.00,
	"total" decimal not null default 0.00,
	"tax_id"  integer not null default 0,
	"tax_amount" decimal not null default  0.00,
	"discount_rate" decimal not null default 0.00,
	"discount_type" varchar(255) not null default '' ,
	is_active smallint DEFAULT 0 NOT NULL,
    is_synced smallint DEFAULT 0 NOT NULL,
    "created_at" timestamp,
	"updated_at" timestamp,
	"deleted_at" timestamp,
	PRIMARY KEY (id)
);